# Generated by Django 2.1.4 on 2019-05-05 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('posted_by', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('experience', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JobsApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='JobsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedinUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=10000)),
                ('postImage', models.CharField(max_length=1000)),
                ('postDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('contactInfo', models.CharField(max_length=50)),
                ('connections', models.ManyToManyField(related_name='_userdetails_connections_+', to='Auth.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='postBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.UserDetails'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Posts'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.UserDetails'),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Posts'),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.UserDetails'),
        ),
        migrations.AddField(
            model_name='loggedinusers',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.UserDetails'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.JobsCategories'),
        ),
    ]
