# Generated by Django 2.1.4 on 2019-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contactInfo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
